### ISSUE TITLE
First install appears to have error; 2002: No such file or directory

### ISSUE THREAD

**Issue by Axodouble** [dragomano/SMF-Docker#1]
![image](https://github.com/dragomano/SMF-Docker/assets/53979495/5c44c77d-d254-45bd-809a-4016ea3be05a)
While attempting to install it with no prior changes and after running docker compose up -d it appears to get this error.

**Comment by dragomano** [comment]
> MySQL | mysql | 3306 (default)

Use `mysql` or `mariadb` instead of `localhost`

**Comment by Axodouble** [comment]
Ah yeah I see, I completely overlooked that. Excuse me haha.
